platform :ios, '10.0'

# ignore all warnings from all dependencies
inhibit_all_warnings!

use_frameworks!
target 'OptionMenu_Tests' do
  pod 'OptionMenu', :path => '../'
  pod 'MaterialComponents/BottomSheet'
  pod 'Localize-Swift'
  
end
